### ISSUE TITLE
Number of the episodes

### ISSUE THREAD

**Issue by fulanumoto** [Animenosekai/japanterebi-xmltv#4]
is it possible to add number of the episodes in the guide `episode-num`, or is that information unavailable from the source?
Thanks.

**Comment by Animenosekai** [comment]
It is impossible for now because the scripts only use the `iptv-org` sources and they don't seem to give this kind of information.

Now that said, I plan to make a script to create archives of the TV guides data. Because I'll be able to manipulate the entries, I might create something which extracts the episode number from the title. I'll then be able to add it to the live XMLTV file.
